<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Qsys.SensorApp.Application\Qsys.SensorApp.Application.csproj" />
    <ProjectReference Include="..\Qsys.SensorApp.Infrastructure\Qsys.SensorApp.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
  </ItemGroup>

</Project>
